{% set name = "dagster_pyspark" %}
{% set version = "0.6.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 5aa216f26d519ae443cb1d7d7c498e11755435d2b9e64226f3f5483ba8ae9cb9

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - dagster {{ version }}.*
    - dagster_spark {{ version }}.*
    - pyspark

test:
  imports:
    - dagster_pyspark

about:
  home: "https://github.com/dagster-io/dagster/tree/master/python_modules/dagster-framework/pyspark"
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "Package for PySpark Dagster framework components."

extra:
  recipe-maintainers:
    - xhochy
